### ISSUE TITLE
SlickQuiz True and False quizzes don't always resolve answer correctly

### ISSUE THREAD

**Issue by Markieta** [CDOT-EDX/Project#120]
The following example resolves to Correct:

``` JSON
{
    "option": "False",
    "correct": false
}
```

See Snap1 Slide 16.

**Comment by pkuzhel** [comment]
As we discussed, this is probably due to one quiz having multiple questions. Backend only resolves one question per quiz.

Option 1: separate quizzes and let each quiz trigger the next one (preffered)
Option 2: extend backend to handle multiple questions (more work and prone to more errors in the future)

**Comment by CDOT-EDX** [comment]
Paul,

Implement the first one and let us try to get approval for it

Jordan

On Wed, Nov 18, 2015 at 11:56 AM, Pavlo Kuzhel notifications@github.com
wrote:

> As we discussed, this is probably due to one quiz having multiple
> questions. Backend only resolves one question per quiz.
> 
> Option 1: separate quizzes and let each quiz trigger the next one
> (preffered)
> Option 2: extend backend to handle multiple questions (more work and prone
> to more errors in the future)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CDOT-EDX/Project/issues/120#issuecomment-157777465.

## 

Jordan Anastasiade
